# Site settings
showheader: false
theme: jekyll-theme-midnight
title: Speech Rule Engine
description: Turning Formulas into Speech
baseurl: ""
url: "https://speechruleengine.org"

# GitHub
repository: speech-rule-engine/speech-rule-engine

plugins:
  - jekyll-github-metadata
